config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  get '/support', to: 'pages#support', as: 'support'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bookings, only: %i[index edit update destroy] do
    member do
      patch :validate
      patch :decline
      patch :pay
      patch :close
      patch :cancel
    end
  end

  resources :ships do
    resources :bookings, only: %i[new create]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  get 'my_ships', to: 'ships#profil', as: :my_ships
end

app/views/shared/_bookingcard.html.erb
<div class="card-product mb-1">
  <%= cl_image_tag booking.ship.photo.key if booking.ship.photo.attached? %>
  <div class="card-product-info w-100">
    <div class="d-flex justify-content-between">
      <div class="card-title">
        <%= "#{booking.ship.name} #{booking.id}" %>
      <!-- Edit button available only if status and start date allow it -->
        <% if (((booking.user_id == current_user.id) && ['pending', 'paid'].include?(booking.status.downcase)) && booking.date_start >= Date.today) && booking.user_id == current_user.id %>
          <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_booking_path(booking), class: "edit pr-2" %>
        <% end %>
      </div>

    </div>
    <div class="d-flex justify-content-around">
      <% unless booking.ship.user.nickname == current_user.nickname  %>
        <div class="to-hide">
          <h2>Owner</h2>
          <div><%= booking.ship.user.nickname.capitalize %></div>
        </div>
      <% end %>
      <% unless booking.user.nickname == current_user.nickname %>
        <div class="to-hide">
          <h2>Requestor</h2>
          <div><%= booking.user.nickname.capitalize %></div>
        </div>
      <% end %>
      <div>
        <h2>Starting Date</h2>
        <div><%= booking.date_start %></div>
      </div>
      <div>
        <h2> Ending Date</h2>
        <div><%= booking.date_end %></div>
      </div>
      <div class="to-hide">
        <h2>Attendants</h2>
        <div> <%= number_with_delimiter(booking.crew_size, delimiter:'.') %></div>
      </div>
      <div>
        <h2>Amount</h2>
        <div> <%= number_with_delimiter(booking.total_amount, delimiter:'.') %> 👾</div>
      </div>
    </div>
    <div class="d-flex justify-content-between card-product-footer px-5">
      <div class="status"><strong><%=booking.status.upcase %></strong></div>
              <% if  booking.ship.user_id == current_user.id && booking.status.downcase == 'pending'%>
        <div class="buttons">
          <%= link_to decline_booking_path(booking), method: :patch, data: { confirm: "Are you sure you want to decline?"} do %>
            <button class = 'btn btn-danger'>☠ Decline ☠</button>
          <% end %>
          <%= link_to validate_booking_path(booking), method: :patch, data: { confirm: "Are you sure you want to accept?"} do %>
            <button class = 'btn btn-success'>🚀 Accept 🚀</button>
          <% end %>
        </div>
        <!-- Cas 2 : Paid / Owner + Date check-->
        <% elsif  booking.ship.user_id == current_user.id && booking.status.downcase == 'paid' && booking.date_end <= Date.today%>
        <div class="buttons d-flex justify-content-around">
          <%= link_to close_booking_path(booking), method: :patch, data: { confirm: "Are you sure you want to close?"} do %>
            <button class = 'btn btn-info'>🔐 Close 🔐</button>
          <% end %>
        </div>
        <!-- Cas 3 : Validated/Owner Validated/User Paid/Owner Paid/User + Date check-->
        <% elsif  ((booking.ship.user_id == current_user.id && ['validated', 'paid'].include?(booking.status.downcase)) || (booking.user_id == current_user.id) && ['pending', 'paid'].include?(booking.status.downcase)) && booking.date_start >= Date.today%>
          <div class="buttons d-flex justify-content-around">
            <%= link_to cancel_booking_path(booking), method: :patch, data: { confirm: "Are you sure you want to cancel? Penalty or no refund if you booked. Cancellation will be remembered if you own..."} do %>
              <button class = 'btn btn-danger'>🤖 Cancel 🤖</button>
            <% end %>
          </div>
          <!-- Cas 4 : Validated status can be paid (or not) by USER -->
          <% elsif  booking.user_id == current_user.id && booking.status.downcase == 'validated'%>
            <div class="buttons d-flex justify-content-around">
            <%= form_tag orders_path do %>
              <%= hidden_field_tag 'booking_id', booking.id %>
              <button class = 'btn btn-info'>👾 Pay 👾</button>
              <% end %>
            </div>
          <!-- Cas 5 : Validated status can be paid (or not) by USER -->
          <% elsif ['cancelled','closed'].include?(booking.status.downcase)%>
            <div class="buttons d-flex justify-content-around">
              <%= link_to support_path do %>
                <button class = 'btn btn-secondary'>👽 Request help 👽</button>
              <% end %>
            </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  Je suis un footer
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon mb-2">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Rent your ship!", new_ship_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Home", ships_path, class: "nav-link" %>
        </li>
        <li class="navbar-text pr-2"><%= current_user.nickname %></li>
        <li class="nav-item dropdown">
          <%= image_tag "https://www.parisduckstore.fr/wp-content/uploads/2020/02/canard-bain-star-wars-min.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My ships", my_ships_path, class: "dropdown-item" %>
            <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_ship_add_edit_form.html.erb
<%= simple_form_for(@ship) do |f| %>
  <!-- <%= f.hidden_field :user_id, value: current_user.id %> -->
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :location %>
  <%= f.input :purpose, collection: ['war', 'holiday', 'race', 'planet eradication', 'galactical space party'] %>
  <%= f.input :size, collection: ['micro', 'small', 'big', 'planetwide'] %>
  <%= f.input :crew_capacity %>
  <%= f.input :price_per_day %>
  <%= f.input :available, :input_html => { :checked => true } %>
  <%= f.input :photo, as: :file %>
  <div class="d-flex">
    <%= link_to "Cancel", ships_path, class: "btn btn-danger w-100 mr-1" %>
    <%= f.submit "Submit", class: "btn btn-primary w-100"%>
  </div>
<% end %>

app/views/shared/_ship_card.html.erb
<%= link_to ship_path(ship.id), class: "card-img" do %>
  <div class="card c-ship" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.1)), url('<%= cl_image_path ship.photo.key if ship.photo.key %>')">
    <h3 class="c-ship-name"><%= ship.name %></h3>
    <div class="c-ship-details">
      <h3 class="d-flex justify-content-end"><%= ship.crew_capacity %> <i class="fas fa-users"></i></h3>
      <h3 class="d-flex justify-content-end"><%= ship.purpose.capitalize if ship.purpose %> 
        <% if ship.purpose == 'war' %>
          <div>
            <i class="fas fa-bomb"></i>
          </div>
        <% elsif ship.purpose == 'holiday' %>
          <div>
            <i class="fas fa-umbrella-beach"></i>
          </div>
        <% elsif ship.purpose == 'galactical space party' %>
          <div>
            <i class="fas fa-glass-cheers"></i>
          </div>
        <% elsif ship.purpose == 'planet eradication' %>
          <div>
            <i class="fas fa-meteor"></i>
          </div>
        <% elsif ship.purpose == 'race' %>
          <div>
            <i class="fas fa-fighter-jet"></i>
          </div>
        <% end %>
      </h3>
      <h3 class="d-flex justify-content-end"><%= ship.size.capitalize %> 
        <% if ship.size == 'micro' %>
          <div>
            <i class="fas fa-atom"></i>
          </div>
        <% elsif ship.size == 'small' %>
          <div>
            <i class="fas fa-dot-circle"></i>
          </div>
        <% elsif ship.size == 'big' %>
          <div>
            <i class="fab fa-docker"></i>
          </div>
        <% elsif ship.size  == 'planetwide' %>
          <div>
            <i class="fas fa-globe"></i>
          </div>
        <% end %>
      </h3>
      <h3 class="d-flex justify-content-end"><%= "#{number_with_delimiter(ship.price_per_day, delimiter: '.')} ₹"%></h3>
    </div>
  </div>
<% end %>