config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  get '/support', to: 'pages#support', as: 'support'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bookings, only: %i[index edit update destroy] do
    member do
      patch :validate
      patch :decline
      patch :pay
      patch :close
      patch :cancel
    end
  end

  resources :ships do
    resources :bookings, only: %i[new create]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  get 'my_ships', to: 'ships#profil', as: :my_ships
end

app/models/ship.rb
class Ship < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  monetize :price_cents
  validates :name, :description, :location, :price_per_day, :size, :crew_capacity, presence: true
  validates :price_per_day, :crew_capacity, numericality: { only_integer: true }
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  before_action :set_ship, only: [:show, :destroy, :edit, :update]
  def index
    @ships = Ship.all.order('name ASC')
    @all_ships = false

    @search = params["search"]
    if @search.present?
      name = @search["name"]
      if name === ""
        @ships = Ship.all.order('name ASC')
        @all_ships = false
      else
        @ships = Ship.global_search(name).order('name ASC')
        @all_ships = true
      end
    end

  end

  def show
    @available_status = available_status(@ship.available)
  end

  def new
    @ship = Ship.new
  end

  def create
    @ship = Ship.new(ship_params)
    user = current_user
    @ship.user = user


    @ship.save

    redirect_to ship_path(@ship)
  end

  def destroy
    @ship.destroy
    redirect_to ships_path
  end

  def edit
    @ship = Ship.find(params[:id])
  end

  def update
    if  @ship.update(ship_params)
      @ship.save
      redirect_to ship_path(@ship)
    else
      render :edit
    end
  end

  def profil
    @ships = Ship.where(user_id: current_user.id).order('name ASC')
    @all_my_ships = false

    @search = params["search"]
    if @search.present?
      name = @search["name"]
      if name === ""
        @ships = Ship.where(user_id: current_user.id).order('name ASC')
        @all_my_ships = false
      else
      @ships = Ship.where(user_id: current_user.id).order('name ASC').global_search(name)
      @all_my_ships = true
      end
    end
  end

  private

  def set_ship
    @ship = Ship.find(params[:id])
  end

  def available_status(available)
    if available
      return "Ce vaisseau est disponible"
    else
      return "Désolé, ce vaisseau n'est pas disponible"
    end
  end

  def ship_params
    params.require(:ship).permit(:name, :description, :location, :purpose, :size, :crew_capacity, :price_per_day, :available, :photo)
  end
end

app/views/ships/edit.html.erb
<div class="container">

  <%= simple_form_for(@ship) do |f| %>
    <div class="d-flex mt-5">
      <div class="form-part w-50 p-3">
  <!-- <%= f.hidden_field :user_id, value: current_user.id %> -->
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :location %>
        <%= f.input :purpose, collection: ['war', 'holiday', 'race', 'planet eradication', 'galactical space party'] %>
        <%= f.input :size, collection: ['micro', 'small', 'big', 'planetwide'] %>
        <%= f.input :crew_capacity %>
      </div>

      <div class='form-card d-block w-50 p-3 mr-3'>
        <div class="form-img d-flex justify-content-center align-items-center">
          <h2>Edit your ship!</h2>
        </div>
        <br>
        <%= f.input :price_per_day %>
        <%= f.input :photo, as: :file, label: 'Choose a nice picture for your ship' %>
        <%= f.input :available, :input_html => { :checked => true }, label: 'Notify users your ship is available!' %>
        <div class="d-flex form-buttons">
          <%= link_to "Cancel", ships_path, class: "btn btn-danger w-100 mr-1" %>
          <%= f.submit "Submit", class: "btn btn-success w-100"%>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/ships/index.html.erb
<div class="container-ship-index">

  <div class="d-flex justify-content-between mt-3">
    <h2 class="ml-3">Ships available</h2>
    <div class="mr-3">
      <%= simple_form_for :search, url: ships_path, method: "GET", html: { class: 'form-inline' } do |f| %>
        <%= f.input :name, input_html: {value: ""}, label: false, placeholder: 'Find the perfect ship...' %>   
        <%= f.submit "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <div class="d-flex justify-content-end mr-3 mb-5">
    <% if @all_ships === true %>
      <div><%= link_to "Back to all ships", ships_path %></div>
    <% end %>
  </div>





  <div class="cards c-index">
    <% @ships.each do |ship| %>
      <%= render 'shared/ship_card', ship: ship %>
    <% end %>
  </div>

  <div class="d-flex m-3">
    <% if @all_ships === true %>
      <%= link_to "All ships", ships_path, class: "btn btn-primary mr-3" %>
    <% end %>
    <%= link_to "My ships", my_ships_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/ships/new.html.erb
<div class="container" id = 'footer-page'>


  <%= simple_form_for(@ship) do |f| %>
    <div class="d-flex mt-5">
      <div class="form-part w-50 p-3">
  <!-- <%= f.hidden_field :user_id, value: current_user.id %> -->
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :location %>
        <%= f.input :purpose, collection: ['war', 'holiday', 'race', 'planet eradication', 'galactical space party'] %>
        <%= f.input :size, collection: ['micro', 'small', 'big', 'planetwide'] %>
        <%= f.input :crew_capacity %>
      </div>

      <div class='form-card d-block w-50 p-3 mr-3'>
        <div class="form-img d-flex justify-content-center align-items-center">
          <h2>Add a new ship!</h2>
        </div>
        <br>
        <%= f.input :price_per_day %>
        <%= f.input :photo, as: :file, label: 'Choose a nice picture for your ship' %>
        <%= f.input :available, :input_html => { :checked => true }, label: 'Notify users your ship is available!' %>
        <div class="d-flex form-buttons">
          <%= link_to "Cancel", ships_path, class: "btn btn-danger w-100 mr-1" %>
          <%= f.submit "Submit", class: "btn btn-success w-100"%>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/ships/profil.html.erb
<div class="container-ship-index" id = 'footer-page'>

  <div class="d-flex justify-content-between mt-3">
    <h2 class="ml-3">My ships</h2>
    <div class="mr-3">
      <%= simple_form_for :search, url: my_ships_path, method: "GET", html: { class: 'form-inline' } do |f| %>
        <%= f.input :name, input_html: {value: ""}, label: false, placeholder: 'Find the perfect ship...' %>
        <%= f.submit "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <div class="d-flex justify-content-end mr-3 mb-5">
    <% if @all_my_ships === true %>
      <div><%= link_to "Back to all my ships", my_ships_path %></div>
    <% end %>
  </div>

  <div class="cards c-index">
    <% @ships.each do |ship| %>
      <div>
        <%= render 'shared/ship_card', ship: ship %>

      </div>
    <% end %>
  </div>

  <div class="d-flex m-3">
    <%= link_to "Add new ship", new_ship_path, class: "btn btn-primary mr-3" %>
    <%= link_to "All ships", ships_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/ships/show.html.erb
<div class="container" id = 'footer-page'>
  <ul class="list-group shadow-sm">
    <li class="list-group-item">
      <div class="d-flex justify-content-between">
        <div class="ss-header-text">
          <div class = 'd-flex justify-content-between align-items-center mb-5'>
            <h2><%= @ship.name %></h2>
            <div class = 'pr-3'>
              <% if current_user.id === @ship.user.id %>
                <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_ship_path(@ship.id), class: "edit pr-2" %>
                <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, ship_path(@ship), method: :delete, data: { confirm: "Are you sure?"}, class: "trash" %>
              <% end %>
            </div>
          </div>
          <div class= 'pt-1'>
            <h5>Description</h5>
            <div><%= @ship.description.capitalize %></div>
            <% if current_user.id === @ship.user.id %>
              <div class="text-center">
                <%= link_to "You can't book your own ship! You intergalactical dumbass.", '#', class: "btn btn-light w-75 mt-5" %>
              </div>
            <% elsif !@ship.available %>
              <div class="text-center">
                <%= link_to "Ship is not available! Come back in a century.", '#', class: "btn btn-light w-75 mt-5" %>
              </div>
            <% else %>
              <div class="text-center">
                <%= link_to "Book it now", new_ship_booking_path(@ship.id), class: "btn btn-primary w-75 mt-5" %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="ss-header-img" style="background-image: url('<%= cl_image_path @ship.photo.key %>')">>
        </div>
      </div>
    </li>
    <div>
      <button id="ss-show-details" class="btn btn-primary w-100">Show details</button>
    </div>
    <div class="d-none" id="ss-ship-details">
      <li class="list-group-item d-flex">
        <h5>Location</h5>
        <div><%= @ship.location.capitalize %></div>
      </li>
      <li class="list-group-item d-flex">
        <h5>Purpose</h5>
        <% if @ship.purpose == 'war' %>
          <div>
            <i class="fas fa-bomb"></i>
            <%=  @ship.purpose.capitalize if @ship.purpose %>
          </div>
        <% elsif @ship.purpose == 'holiday' %>
          <div>
            <i class="fas fa-umbrella-beach"></i>
            <%=  @ship.purpose.capitalize if @ship.purpose %>
          </div>
        <% elsif @ship.purpose == 'galactical space party' %>
          <div>
            <i class="fas fa-glass-cheers"></i>
            <%=  @ship.purpose.capitalize if @ship.purpose %>
          </div>
        <% elsif @ship.purpose == 'planet eradication' %>
          <div>
            <i class="fas fa-meteor"></i>
            <%=  @ship.purpose.capitalize if @ship.purpose %>
          </div>
        <% elsif @ship.purpose == 'race' %>
          <div>
            <i class="fas fa-fighter-jet"></i>
            <%=  @ship.purpose.capitalize if @ship.purpose %>
          </div>
        <% end %>
      </li>
      <div class="d-flex">
        <li class="list-group-item w-50 d-flex">
          <h5>Size</h5>
        <% if @ship.size == 'micro' %>
          <div>
            <i class="fas fa-atom"></i>
            <%=  @ship.size.capitalize if @ship.size %>
          </div>
        <% elsif @ship.size == 'small' %>
          <div>
            <i class="fas fa-dot-circle"></i>
            <%=  @ship.size.capitalize if @ship.size %>
          </div>
        <% elsif @ship.size == 'big' %>
          <div>
            <i class="fab fa-docker"></i>
            <%=  @ship.size.capitalize if @ship.size %>
          </div>
        <% elsif @ship.size  == 'planetwide' %>
          <div>
            <i class="fas fa-globe"></i>
            <%=  @ship.size.capitalize if @ship.size %>
          </div>
        <% end %>
        </li>
        <li class="list-group-item w-50 d-flex">
          <h5>Crew capacity</h5>
          <div><%= number_with_delimiter(@ship.crew_capacity, delimiter: '.') %></div>
        </li>
      </div>
      <li class="list-group-item d-flex">
        <h5>Price per day</h5>
        <div><%= "#{number_with_delimiter(@ship.price_per_day, delimiter: '.')} ₹"%></div>
      </li>
      <li class="list-group-item d-flex">
        <h5>Availability</h5>
        <div><%= @available_status %></div>
      </li>
    </div>
  </ul>


  <div class="d-flex m-3">
    <%= link_to "All ships", ships_path, class: "btn btn-primary mr-3" %>
    <%= link_to "My ships", my_ships_path, class: "btn btn-primary" %>
  </div>

</div>